### PR TITLE
Patrick/fix

### PR DESCRIPTION
**Pull request by irishpatrick**
This should fix the "framebuffer not complete" error.

### CODE REVIEW

**Comment by sona-padin** [comment]
I've tried to run your branch on my other machine that had the framebuffer bug but unfortunately, I couldn't get this code running on my machine. Hopefully, Ilana has better luck running it on her machine. Don't worry, we will figure something out!!

**Comment by irishpatrick** [comment]
Strange, was the error message any different this time? Also did the window open, or just crash?

**Comment by sona-padin** [comment]
Same error on my end and the window just crashes

**Comment by irishpatrick** [comment]
Can you post the terminal output? I'm hoping it's just a version error

**Review by sona-padin — APPROVED** [review]
I just ran it again on VirtualBox, and it works!!

**Pull request merged**
